name: Github Packages
on:
  release:
    types: [created]
jobs:
  gh_packages:
    name: 'On Release - Release version GH Packages'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      # Setup .npmrc file to publish to GitHub Packages
      - name: Setup configuration for GH Packages
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dankreiger'
      # Publish to GitHub Packages
      - run: npm publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}